export const myData = [
  { text: "Courses", value: "cou" },
  { text: "Cyber Security", value: "cyb" },
  { text: "Graphics Design", value: "gra" },
  { text: "Video Animation", value: "vid" },
  { text: "Frontend Development", value: "fro" },
  { text: "Backend Development", value: "bac" },
  { text: "Data Science", value: "dat" },
  { text: "Ui/Ux Design", value: "uiu" },
  { text: "Machine Learning", value: "mac" },
  { text: "App Development", value: "app" },
  { text: "Digital Marketing", value: "dig" },
  { text: "Content Creation", value: "con" },
  { text: "2D/3D Illustration", value: "2d3" },
  { text: "Python for Database", value: "pyt" },
  { text: "Virtual Assistance", value: "vir" },
  { text: "Motion Graphics", value: "mot" },
  { text: "Basic ICT", value: "bas" },
];
